name: CI pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node js envt
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install dependencies
        run: yarn install --frozen-lockfile

      - name: run lint
        run: yarn lint

      - name: ❗️ DEBUG - Check Environment Variables
        run: |
          echo "--- Checking for API_URL ---"
          if [ -z "$API_URL" ]; then
            echo "API_URL is NOT SET"
          else
            echo "API_URL is set to: $API_URL"
          fi

          echo "--- Checking for AUTH_SECRET ---"
          if [ -z "$AUTH_SECRET" ]; then
            echo "AUTH_SECRET is NOT SET"
          else
            echo "AUTH_SECRET is set to: [REDACTED]"
          fi

      - name: run tests
        run: yarn test

      - name: build project
        run: yarn build
